export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PRODUCTS_ROUTE = '/product'
export const CURRENT_PRODUCT_ROUTE = '/product/'
export const NOT_FOUND_ROUTE = '*'